\documentclass[letterpaper]{article}

\usepackage{fancyvrb}
\usepackage{fullpage}
\usepackage{listings}
\usepackage{xcolor}
\usepackage{float}
\usepackage{hyperref}

\lstset{basicstyle=\ttfamily, 
        backgroundcolor=\color[gray]{0.95}}
        
\author{Michael Gruenstaeudl, Nils Jenke}
\title{Using the PACViR Pipeline}

\begin{document}
\SweaveOpts{concordance=TRUE}
%\SweaveUTF8

<<echo=FALSE>>=
  options(width=60, size="scriptsize")
@

\maketitle

\tableofcontents

\section{Introduction}

  The PACViR pipeline generates a visualization of a plastome in a circular fashion. This vignette provides two examples of   how to execute PACViR via the R function 'PACViR.complete()' and via bash.

\section{Requirements}

  To execute PACViR several requirements have to be installed.


  \begin{footnotesize}
  \begin{lstlisting}[linerange=\\begin\{Sinput\}-\\end\{Sinput\},includerangemarker=false]
<<>>=
    #library(PACViR)

@
  \end{lstlisting}
  \end{footnotesize}


\section{PACViR via R-function }

  PACViR can be easily executed via the PACViR.complete() function in R. Therefore one can load the provided data from the package.

  \begin{footnotesize}
  \begin{lstlisting}[linerange=\\begin\{Sinput\}-\\end\{Sinput\},includerangemarker=false]
<<>>=
    # The absolute path to the input directory is set
    inPath <- system.file("extdata", "MH161174/", package="PACViR")

    # The names of the input files located in inPath are set
    inFile_gb  <- "MH161174.gb"
    inFile_bam <- "MH161174.bam"
    
    gbk.file <- paste(inPath,"/",inFile_gb)
    bam.file <- paste(inPath,"/",inFile_bam)
    windowSize <- 250
    mosdepthCmd <- "mosdepth"
    threshold <- 15 
    delete <- "TRUE"
    outDir <- "./output"
    #PACViR.complete(gbk.file, bam.file, windowSize, mosdepthCmd, threshold, delete, outDir)
@
  \end{lstlisting}
  \end{footnotesize}
  

%  \begin{figure}[H]
%  \centering
%    \includegraphics{}
%    \caption{Visualization of SCHM2 plastome with PACViR.complete()}
%  \centering
%  \end{figure}

\section{PACViR via command line}

  Execute PACViR\_Rscript.R via command line with Rscript.
  
\begin{footnotesize}
\begin{lstlisting}
  Rscript PACViR_Rscript.R  -k ../inst/extdata/DAS01.gb -b ../inst/extdata/DAS01.bam 
\end{lstlisting}
\end{footnotesize}

%  \begin{figure}[H]
%  \centering
%    \includegraphics{}
%    \caption{Visualization of DAS01 plastome with Rscript}
%  \centering
%  \end{figure}
  
\section{Modifying parameters}

  Depending on which system PACViR will be executed

\section{More Information}

\section{sessionInfo}

<<>>=
sessionInfo()
@

\end{document}